# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enzymes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sequence', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(help_text='Enter sequence of your insert:')),
            ],
        ),
        migrations.CreateModel(
            name='Plasmids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sequence', models.TextField()),
            ],
        ),
    ]
